---
- name: SWAP | Check if swap file exists
  stat:
    path: "{{ rpi_swap_filepath }}"
  register: result

- name: SWAP | Unmount swap file
  command: dphys-swapfile swapoff && dphys-swapfile uninstall
  when: result.stat.exists

- name: SWAP | Stop and disable dphys-swapfile service
  service:
    name: dphys-swapfile
    state: stopped
    enabled: no
